---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu
    apt: 
      name: apache2
      state: present
      
  - name: start webserver
    service:
      name: apache2
      state: started

